global:
  name: consul
  datacenter: dc-k8s
  tls:
    enabled: true
    caCert:
      secretName: consul-federation
      secretKey: caCert
    caKey:
      secretName: consul-federation
      secretKey: caKey

  federation:
    enabled: true
controller:
  enabled: true
connectInject:
  enabled: true
meshGateway:
  enabled: true
server:
  extraConfig: |
    {
      "primary_datacenter": "dc-vm",
      "primary_gateways": ["<gateway-ip>:8443"]
    }
